### ISSUE TITLE
Enhancements tracker

### ISSUE THREAD

**Issue by 5310** [onnyyonn/feed#2]
A few future enhancements to the site. 

(I had these on the readme, but it makes more sense as an Issue since we're tied to GitHub anyway...)

- [x] Add link to GH-Pages to the repo descriptions :]
- [x] Add a daily GH-Action to rebuild the site for now
- [x] Make the [SVG favicon](src/favicon.svg) responsive so that it's actually visible at small scales
- [x] Make Lume copy static assets with globs

**Comment by 5310** [comment]
Really shouldn't be doing this in bed...

**Comment by 5310** [comment]
I'm going to extract the local feed task into its own Issue and close this.
